---

league_api_url: local.league-api.com
league_api_runmode: development
league_api_docroot: /var/www/league-api
league_api_log_directory: /home/exampleuser/logs
league_api_deploy_host: local.league-api.com
league_api_deploy_user: exampleuser
league_api_db_name: league-api
league_api_backup_directory: /home/exampleuser/backups

league_frontend_url: local.league-frontend.com
league_frontend_runmode: development
league_frontend_docroot: /var/www/league-frontend
league_frontend_log_directory: /home/exampleuser/logs
league_frontend_deploy_host: local.league-frontend.com
league_frontend_deploy_user: exampleuser
league_frontend_db_name: league-frontend
league_frontend_backup_directory: /home/exampleuser/backups
